# The target name is most likely the name of your project.
target 'iOSAndRN' do

  # Your 'node_modules' directory is probably in the root of your project,
  # but if not, adjust the `:path` accordingly
  pod 'React', :path => './node_modules/react-native', :subspecs => [
  'Core',
  'RCTImage',
  'RCTNetwork',
  'RCTText',
  'RCTWebSocket',

  # Add any other subspecs you want to use in your project
  ]
end
